name: IBM Cloud Auto Install

on:
  workflow_dispatch:
    inputs:

jobs:
  ibm-cloud-install:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Submodule Update Git 
      run: |
        git submodule update --init --recursive

    - name: Settings Configuration File
      run: |
        sed -i "s/cloud_fonudray_name/${{ secrets.IBM_APP_NAME }}/g" ${GITHUB_WORKSPACE}/manifest.yml
        sed -i "s/cloud_fonudray_mem/256/g" ${GITHUB_WORKSPACE}/manifest.yml
        sed -i "s/1200/8080/g" ${GITHUB_WORKSPACE}/RSSHub/lib/config.js

    - name: Install RSSHub Dependencies
      run: |
        mkdir ~/.npm-global
        npm config set prefix '~/.npm-global'
        sed -i '$a\export PATH=~/.npm-global/bin:$PATH' ~/.profile
        source ~/.profile
        cd ${GITHUB_WORKSPACE}/RSSHub
        npm i
        cd ..

    - name: Install Cloud Foundry CLI
      run: |
        curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github&version=v6" | tar -zx
        sudo mv cf /usr/local/bin
      
    - name: Login Cloud Foundry
      run: cf l -a https://api.us-south.cf.cloud.ibm.com login -u ${{ secrets.IBM_MAIL }} -p ${{ secrets.IBM_PWD }}
      
    - name: Push Cloud Foundry APP
      run: |
        cf push ${{ secrets.IBM_APP_NAME }}
